name: Build Linux Executable

on:
  workflow_dispatch:   # 允许在 GitHub Actions 页面手动触发

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux executable
        run: |
          # 使用 fofa.py 作为入口脚本生成单文件可执行程序
          pyinstaller --onefile fofa.py
          # 打包成 zip，名字带程序名
          zip -r fofa_hack-linux.zip dist/fofa

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          # 每次手动触发都会生成唯一 tag
          tag: manual-${{ github.run_id }}
          name: "Linux Release #${{ github.run_id }}"
          body: "手动触发生成的 fofa_hack Linux 可执行文件"
          files: |
            fofa_hack-linux.zip
