name: Build Linux Executable

on:
  workflow_dispatch:   # 允许手动触发

jobs:
  build-linux:
    runs-on: ubuntu-latest   # 外层 runner 使用默认即可

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install gh CLI
        run: |
          sudo apt-get update && sudo apt-get install -y gh

      - name: Build Linux executable in Debian 12 Docker
        run: |
          # 在 Debian 12 (Bullseye) Docker 容器中打包
          docker run --rm -v $PWD:/src -w /src python:3.8-slim-bullseye bash -c "
            apt-get update && apt-get install -y build-essential pyinstaller
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pyinstaller --onefile fofa.py
            mv dist/fofa dist/fofa-hack_linux_amd64
          "

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 使用唯一 tag 避免重复
          TAG_NAME="manual-${GITHUB_RUN_ID}-$(date +%s)"
          gh release create $TAG_NAME dist/fofa-hack_linux_amd64 \
            --title "Linux Release #${GITHUB_RUN_ID}" \
            --notes "手动触发生成的 fofa_hack Linux 可执行文件 (Debian 12 compatible)"
