name: Build Linux Executable

on:
  workflow_dispatch:   # 手动触发

jobs:
  build-linux:
    runs-on: ubuntu-20.04   # 低版本 glibc，兼容性好

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          sudo apt-get update && sudo apt-get install -y gh

      - name: Build Linux executable
        run: |
          # 打包 fofa.py 为单文件可执行程序
          pyinstaller --onefile fofa.py
          # 重命名生成的可执行文件
          mv dist/fofa dist/fofa-hack_linux_amd64

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 生成唯一 tag，避免重复
          TAG_NAME="manual-${GITHUB_RUN_ID}-$(date +%s)"
          gh release create $TAG_NAME dist/fofa-hack_linux_amd64 \
            --title "Linux Release #${GITHUB_RUN_ID}" \
            --notes "手动触发生成的 fofa_hack Linux 可执行文件"
